# Gems
gems:             [jekyll-paginate, jekyll-gist]
# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            Flannel's
tagline:          'A Flannel blog'
description:      'A blog about IT and Technology'
url:              http://dflannel.it
baseurl:          /

author:
  name:           'Davide Parisi'
  url:            https://twitter.com/slevin
  twitter:        'slevin'

paginate:         5

# Custom vars
version:          0.0.1

github:
  repo:           https://github.com/poole/hyde

include:
  - .well-known
exclude:
  - jekyll.thor
  - LICENSE.md
  - README.md