# Gems
gems:             [jekyll-paginate, jekyll-gist]
# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            Flannel's
tagline:          'A Flannel blog'
description:      'A blog about IT and Technology'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Davide Parisi'
  url:            https://twitter.com/slevin

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

include:
  - .well-known
